use_frameworks!

platform :ios, '9.0'

target 'PowerplayToastKit_Example' do
  pod 'PowerplayToastKit', :path => '../'

  target 'PowerplayToastKit_Tests' do
    inherit! :search_paths

    
  end
end
